version: '3.8'

services:
  mysql:
    image: mysql:8.2
    container_name: budokan-be-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: budokan
      MYSQL_DATABASE: budokan-db
      MYSQL_USER: budokan
      MYSQL_PASSWORD: budokan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local 