version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budokan-be-app
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql://budokan:budokan@mysql:3306/budokan-db
      - DATABASE_URL_FROM_CONTAINER=mysql://budokan:budokan@mysql:3306/budokan-db
      - JWT_SECRET=beb52a940d2eb3fb91488adac8b3f265dcec56daf6db0ff8ba3ef05ac430e28b
      - NODE_ENV=production
      - DEV_URL=http://localhost:3000
      - PROD_URL=https://api.budokanryu.com.br
      - PORT=8001
      - ETHEREAL_USER=elmore.gleichner32@ethereal.email
      - ETHEREAL_PASS=c1mW6NbsAVxaKAuDtK
      - GMAIL_USER=budokanryu.suporte@gmail.com
      - GMAIL_APP_PASSWORD="ebny zgyr pnnf bxhp"
      - NODE_OPTIONS=--no-warnings
      - DOCKER_BUILDKIT=1
      # Cloudflare Configuration (para produção)
      - BASE_URL=http://localhost:8001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - budokan-network
    volumes:
      - /home/budokan/budokan-data/uploads:/app/uploads

  mysql:
    image: mysql:8.2
    container_name: budokan-be-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: budokan
      MYSQL_DATABASE: budokan-db
      MYSQL_USER: budokan
      MYSQL_PASSWORD: budokan
    ports:
      - "3306:3306"
    volumes:
      - /home/budokan/budokan-data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "budokan", "-pbudokan"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    networks:
      - budokan-network

networks:
  budokan-network:
    driver: bridge

