table instructors {
  id serial [pk, not null, increment]
  user_id "bigint unsigned" [not null]
  bio text
  rank varchar(50)
}

table students {
  id serial [pk, not null, increment]
  user_id "bigint unsigned"
  birth_date date [not null]
  belt varchar(20) [default: 'white']
  emergency_contact varchar(100)
}

table users_table {
  id serial [pk, not null, increment]
  name varchar(100) [not null]
  email varchar(150) [not null, unique]
  password_hash varchar(255) [not null]
  role varchar(20) [not null]
  status varchar(20) [default: 'inactive']
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime
}

ref: instructors.user_id - users_table.id

ref: students.user_id - users_table.id